stages:
  - build
  - publish

variables:
  PACKAGE_NAME: system-monitor
  VERSION: "1.0"
  ARCH: all
  BUILD_DIR: build/${PACKAGE_NAME}
  OUTPUT_DIR: build/output
  DEB_FILE: ${OUTPUT_DIR}/${PACKAGE_NAME}_${VERSION}.deb
  CI_API_V4_URL: https://gitlab.example.com/api/v4
  DIST: stable
  COMPONENT: main

build_deb:
  stage: build
  image: sp-dk-reg.seaproject.ru/tech-img-01:latest
  script:
    - apt update && apt install -y dpkg-dev
    - mkdir -p ${BUILD_DIR}/DEBIAN
    - cp -r zephyr_monitor/* ${BUILD_DIR}/
    - chmod +x ${BUILD_DIR}/usr/local/bin/system-monitor.sh
    - |
      cat > ${BUILD_DIR}/DEBIAN/control <<EOF
      Package: ${PACKAGE_NAME}
      Version: ${VERSION}
      Section: base
      Priority: optional
      Architecture: ${ARCH}
      Maintainer: You <dromashko@seaproject.ru>
      Description: System Monitor service
      EOF
    - mkdir -p ${OUTPUT_DIR}
    - dpkg-deb --build ${BUILD_DIR} ${DEB_FILE}
  artifacts:
    paths:
      - ${DEB_FILE}
    expire_in: 1 week

publish_deb:
  stage: publish
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file ${DEB_FILE} \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/debian/pool/${DIST}/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
  needs: [build_deb]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
