stages:
  - build
  - deploy

variables:
  PACKAGE_NAME: system-monitor
  VERSION: "1.0"
  ARCH: all
  BUILD_DIR: build/${PACKAGE_NAME}
  OUTPUT_DIR: build/output

build_deb:
  stage: build
  image:
    name: sp-dk-reg.seaproject.ru/tech-img-01:latest
    # entrypoint: ["/bin/bash", "-c"]
  script:
    - apt update && apt install -y dpkg-dev
    - mkdir -p ${BUILD_DIR}/DEBIAN
    - cp -r zephyr_monitor/* ${BUILD_DIR}/
    - chmod +x ${BUILD_DIR}/usr/local/bin/system-monitor.sh
    - chmod +x ${BUILD_DIR}/usr/bin/camera
    - |
      cat > ${BUILD_DIR}/DEBIAN/control <<EOF
      Package: ${PACKAGE_NAME}
      Version: ${VERSION}
      Section: base
      Priority: optional
      Architecture: ${ARCH}
      Maintainer: You <dromashko@seaproject.ru>
      Description: System Monitor service
      EOF
    - mkdir -p ${OUTPUT_DIR}
    - dpkg-deb --build ${BUILD_DIR} ${OUTPUT_DIR}/${PACKAGE_NAME}_${VERSION}.deb
  artifacts:
    paths:
      - ${OUTPUT_DIR}/${PACKAGE_NAME}_${VERSION}.deb
    expire_in: 1 week

# after_script:
#   - echo "Отчистка временных файлов"
#   - rm -rf build/

# deploy:
#   stage: deploy
#   script:
