stages:
  - build
  - deploy

variables:
  PACKAGE_NAME: system-monitor
  VERSION: "1.0"
  ARCH: all
  BUILD_DIR: build/${PACKAGE_NAME}
  OUTPUT_DIR: build/output

build_deb:
  stage: build
  image: debian:bullseye
